version: '3.4'

services:
  node: 
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/usr/app
    networks:
      my-network:
  postgres:
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./:/usr/app
    networks:
      my-network:
  watchtower:
    image: containrrr/watchtower 
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  i-dont-know:

networks:
  my-network: